version: "3.7"

services:
  frontend:
    image: node:13
    working_dir: /app
    volumes:
      - ${PWD}/frontend:/app
    ports:
      - "8100:3000"
    command: "yarn prod"

  backend:
    build:
      dockerfile: dev.dockerfile
      context: ./backend
      args:
        extras: "[dev]"
    environment:
      WIRVSVIRUS_HOST: "0.0.0.0"
      WIRVSVIRUS_DB_URL: "mongodb://db:27017/default"
      WIRVSVIRUS_AUTH_ENABLED: "false"
    command: "wirvsvirus api --reload"
    volumes:
      - './backend/wirvsvirus:/home/app/code/wirvsvirus'
      - './backend/tests:/home/app/code/tests'
    ports:
      - "8000:8000"
    # need this to enable attaching to container and interacting with debugger
    stdin_open: true
    tty: true

  db:
    image: mongo:3.6
