version: "3.7"

services:
  node:
    image: node:13
    working_dir: /app
    volumes:
      - ${PWD}/:/app

  backend:
    build:
      context: ./backend
      args:
        extras: "[dev]"
    environment:
      WIRVSVIRUS_HOST: "0.0.0.0"
    command: "wirvsvirus api --reload"
    volumes:
      - './backend/wirvsvirus:/home/app/code/wirvsvirus'
    ports:
      - "127.0.0.1:8000:8000"
    # need this to enable attaching to container and interacting with debugger
    stdin_open: true
    tty: true
